<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>BROS_ECommerce.Web</RootNamespace>
    <UserSecretsId>2789a10d-4e60-488b-ac17-3b27b8dadd79</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerComposeProjectPath>..\docker-compose.dcproj</DockerComposeProjectPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="mercadopago-sdk" Version="2.8.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.5">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.5">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
    <PackageReference Include="Stripe.net" Version="48.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BROS-ECommerce.Domain\BROS-ECommerce.Domain.csproj" />
    <ProjectReference Include="..\BROS-ECommerce.Infra\BROS-ECommerce.Infra.csproj" />
    <ProjectReference Include="..\BROS-ECommerce.Services\BROS-ECommerce.Services.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Areas\Administrativo\Views\Shared\Script\" />
  </ItemGroup>

</Project>
