services:
  bros-ecommerce.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_HTTP_PORTS=${WEB_HTTP_PORT}
      - ASPNETCORE_HTTPS_PORTS=${WEB_HTTPS_PORT}
    ports:
      - "${WEB_HTTP_PORT}:${WEB_HTTP_PORT}"
      - "${WEB_HTTPS_PORT}:${WEB_HTTPS_PORT}"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/https:ro