// <auto-generated />
using System;
using BROS_ECommerce.Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BROS_ECommerce.Infra.Migrations
{
    [DbContext(typeof(BrosContext))]
    [Migration("20250716020145_CreateCategoriaTable")]
    partial class CreateCategoriaTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BROS_ECommerce.Domain.Entities.Carrinho", b =>
                {
                    b.Property<Guid>("IdCarrinho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdCarrinho");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("DataCriacao")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid?>("IdUsuario")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdUsuario");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Aberto")
                        .HasColumnName("Status");

                    b.HasKey("IdCarrinho");

                    b.HasIndex("DataCriacao")
                        .HasDatabaseName("IX_Carrinhos_DataCriacao");

                    b.HasIndex("IdUsuario")
                        .HasDatabaseName("IX_Carrinhos_IdUsuario");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Carrinhos_Status");

                    b.ToTable("Carrinhos", (string)null);
                });

            modelBuilder.Entity("BROS_ECommerce.Domain.Entities.CarrinhoItem", b =>
                {
                    b.Property<Guid>("IdCarrinhoItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdCarrinhoItem");

                    b.Property<Guid>("IdCarrinho")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdCarrinho");

                    b.Property<Guid>("IdProduto")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdProduto");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PrecoUnitario");

                    b.Property<int>("Quantidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("Quantidade");

                    b.HasKey("IdCarrinhoItem");

                    b.HasIndex("IdCarrinho")
                        .HasDatabaseName("IX_CarrinhoItens_IdCarrinho");

                    b.HasIndex("IdProduto")
                        .HasDatabaseName("IX_CarrinhoItens_IdProduto");

                    b.HasIndex("IdCarrinho", "IdProduto")
                        .IsUnique()
                        .HasDatabaseName("IX_CarrinhoItens_CarrinhoProduto");

                    b.ToTable("CarrinhoItens", (string)null);
                });

            modelBuilder.Entity("BROS_ECommerce.Domain.Entities.Categoria", b =>
                {
                    b.Property<Guid>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdCategoria");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Ativo");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataAtualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("DataCriacao")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Descricao");

                    b.Property<string>("NomeCategoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("NomeCategoria");

                    b.HasKey("IdCategoria");

                    b.HasIndex("Ativo")
                        .HasDatabaseName("IX_Categorias_Ativo");

                    b.HasIndex("DataCriacao")
                        .HasDatabaseName("IX_Categorias_DataCriacao");

                    b.HasIndex("NomeCategoria")
                        .HasDatabaseName("IX_Categorias_NomeCategoria");

                    b.ToTable("Categorias", (string)null);
                });

            modelBuilder.Entity("BROS_ECommerce.Domain.Entities.CategoriaProduto", b =>
                {
                    b.Property<Guid>("IdCategoriaProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdCategoriaProduto");

                    b.Property<DateTime>("DataAssociacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("DataAssociacao")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("IdCategoria")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdCategoria");

                    b.Property<Guid>("IdProduto")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdProduto");

                    b.HasKey("IdCategoriaProduto");

                    b.HasIndex("DataAssociacao")
                        .HasDatabaseName("IX_CategoriaProdutos_DataAssociacao");

                    b.HasIndex("IdCategoria")
                        .HasDatabaseName("IX_CategoriaProdutos_IdCategoria");

                    b.HasIndex("IdProduto")
                        .HasDatabaseName("IX_CategoriaProdutos_IdProduto");

                    b.HasIndex("IdCategoria", "IdProduto")
                        .IsUnique()
                        .HasDatabaseName("IX_CategoriaProdutos_CategoriasProduto");

                    b.ToTable("CategoriaProdutos", (string)null);
                });

            modelBuilder.Entity("BROS_ECommerce.Domain.Entities.Estoque", b =>
                {
                    b.Property<Guid>("IdEstoque")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdEstoque");

                    b.Property<Guid>("IdProduto")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdProduto");

                    b.Property<int>("Quantidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("Quantidade");

                    b.Property<DateTime>("UltimaAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("UltimaAtualizacao")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("IdEstoque");

                    b.HasIndex("IdProduto")
                        .IsUnique()
                        .HasDatabaseName("IX_Estoque_IdProduto");

                    b.HasIndex("Quantidade")
                        .HasDatabaseName("IX_Estoque_Quantidade");

                    b.HasIndex("UltimaAtualizacao")
                        .HasDatabaseName("IX_Estoque_UltimaAtualizacao");

                    b.ToTable("Estoque", (string)null);
                });

            modelBuilder.Entity("BROS_ECommerce.Domain.Entities.Imagem", b =>
                {
                    b.Property<Guid>("IdImagem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdImagem");

                    b.Property<string>("AltText")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("AltText");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Ativo");

                    b.Property<string>("CaminhoArquivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("CaminhoArquivo");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataAtualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("DataCriacao")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("NomeArquivo");

                    b.Property<long>("TamanhoArquivo")
                        .HasColumnType("bigint")
                        .HasColumnName("TamanhoArquivo");

                    b.Property<string>("TipoMime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("TipoMime");

                    b.HasKey("IdImagem");

                    b.HasIndex("Ativo")
                        .HasDatabaseName("IX_Imagens_Ativo");

                    b.HasIndex("DataCriacao")
                        .HasDatabaseName("IX_Imagens_DataCriacao");

                    b.HasIndex("NomeArquivo")
                        .HasDatabaseName("IX_Imagens_NomeArquivo");

                    b.HasIndex("TipoMime")
                        .HasDatabaseName("IX_Imagens_TipoMime");

                    b.ToTable("Imagens", (string)null);
                });

            modelBuilder.Entity("BROS_ECommerce.Domain.Entities.Pedido", b =>
                {
                    b.Property<Guid>("IdPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdPedido");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataAtualizacao");

                    b.Property<DateTime?>("DataCancelamento")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataCancelamento");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("DataCriacao")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("DataPedido")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataPedido");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdUsuario");

                    b.Property<string>("MotivoCancelamento")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("MotivoCancelamento");

                    b.Property<string>("NumeroPedido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("NumeroPedido");

                    b.Property<string>("ObservacoesInternas")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("ObservacoesInternas");

                    b.Property<string>("ObservacoesPedido")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("ObservacoesPedido");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("Pendente")
                        .HasColumnName("Status");

                    b.Property<decimal>("ValorDesconto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("ValorDesconto");

                    b.Property<decimal>("ValorFrete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("ValorFrete");

                    b.Property<decimal>("ValorSubtotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ValorSubtotal");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ValorTotal");

                    b.HasKey("IdPedido");

                    b.HasIndex("DataCriacao")
                        .HasDatabaseName("IX_Pedidos_DataCriacao");

                    b.HasIndex("DataPedido")
                        .HasDatabaseName("IX_Pedidos_DataPedido");

                    b.HasIndex("IdUsuario")
                        .HasDatabaseName("IX_Pedidos_IdUsuario");

                    b.HasIndex("NumeroPedido")
                        .IsUnique()
                        .HasDatabaseName("IX_Pedidos_NumeroPedido");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Pedidos_Status");

                    b.HasIndex("IdUsuario", "DataPedido")
                        .HasDatabaseName("IX_Pedidos_UsuarioData");

                    b.ToTable("Pedidos", (string)null);
                });

            modelBuilder.Entity("BROS_ECommerce.Domain.Entities.PedidoItem", b =>
                {
                    b.Property<Guid>("IdPedidoItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdPedidoItem");

                    b.Property<Guid>("IdPedido")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdPedido");

                    b.Property<Guid>("IdProduto")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdProduto");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PrecoUnitario");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int")
                        .HasColumnName("Quantidade");

                    b.Property<decimal>("ValorDesconto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("ValorDesconto");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ValorTotal");

                    b.HasKey("IdPedidoItem");

                    b.HasIndex("IdPedido")
                        .HasDatabaseName("IX_PedidoItens_IdPedido");

                    b.HasIndex("IdProduto")
                        .HasDatabaseName("IX_PedidoItens_IdProduto");

                    b.HasIndex("IdPedido", "IdProduto")
                        .HasDatabaseName("IX_PedidoItens_PedidoProduto");

                    b.ToTable("PedidoItens", (string)null);
                });

            modelBuilder.Entity("BROS_ECommerce.Domain.Entities.Produto", b =>
                {
                    b.Property<Guid>("IdProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdProduto");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("Descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Nome");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Preco");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Slug");

                    b.Property<string>("TituloDescricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("TituloDescricao");

                    b.HasKey("IdProduto");

                    b.HasIndex("Nome")
                        .HasDatabaseName("IX_Produtos_Nome");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("IX_Produtos_Slug");

                    b.ToTable("Produtos", (string)null);
                });

            modelBuilder.Entity("BROS_ECommerce.Domain.Entities.ProdutoImagem", b =>
                {
                    b.Property<Guid>("IdProdutoImagem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdProdutoImagem");

                    b.Property<DateTime>("DataAssociacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("DataAssociacao")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("IdImagem")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdImagem");

                    b.Property<Guid>("IdProduto")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdProduto");

                    b.Property<int>("Ordem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("Ordem");

                    b.Property<bool>("Principal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("Principal");

                    b.HasKey("IdProdutoImagem");

                    b.HasIndex("IdImagem")
                        .HasDatabaseName("IX_ProdutoImagens_IdImagem");

                    b.HasIndex("IdProduto")
                        .HasDatabaseName("IX_ProdutoImagens_IdProduto");

                    b.HasIndex("IdProduto", "Ordem")
                        .HasDatabaseName("IX_ProdutoImagens_IdProduto_Ordem");

                    b.HasIndex("IdProduto", "Principal")
                        .HasDatabaseName("IX_ProdutoImagens_UnicaPrincipal")
                        .HasFilter("Principal = 1");

                    b.ToTable("ProdutoImagens", (string)null);
                });

            modelBuilder.Entity("BROS_ECommerce.Domain.Entities.Promocao", b =>
                {
                    b.Property<Guid>("IdPromocao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdPromocao");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Ativo");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataAtualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("DataCriacao")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataFim");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataInicio");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Descricao");

                    b.Property<Guid>("IdProduto")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdProduto");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Nome");

                    b.Property<decimal>("PercentualDesconto")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("PercentualDesconto");

                    b.Property<decimal?>("ValorDesconto")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ValorDesconto");

                    b.HasKey("IdPromocao");

                    b.HasIndex("Ativo")
                        .HasDatabaseName("IX_Promocoes_Ativo");

                    b.HasIndex("DataFim")
                        .HasDatabaseName("IX_Promocoes_DataFim");

                    b.HasIndex("DataInicio")
                        .HasDatabaseName("IX_Promocoes_DataInicio");

                    b.HasIndex("IdProduto")
                        .HasDatabaseName("IX_Promocoes_IdProduto");

                    b.HasIndex("IdProduto", "DataInicio", "DataFim", "Ativo")
                        .HasDatabaseName("IX_Promocoes_ProdutoVigencia");

                    b.ToTable("Promocoes", (string)null);
                });

            modelBuilder.Entity("BROS_ECommerce.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("Nascimento")
                        .HasColumnType("date");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("IdUser");

                    b.HasIndex("Ativo")
                        .HasDatabaseName("IX_Users_Ativo");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Cpf");

                    b.HasIndex("DataCriacao")
                        .HasDatabaseName("IX_Users_DataCriacao");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            IdUser = new Guid("11111111-1111-1111-1111-111111111111"),
                            Ativo = true,
                            Cpf = "12345678901",
                            DataCriacao = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@bros.com",
                            Genero = "Masculino",
                            Nascimento = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Administrador Sistema",
                            Senha = "sRZL6wOaZHF0L6wOaZHF0L6wOaZHF0L6wOaZHF0L6wOaZHF="
                        },
                        new
                        {
                            IdUser = new Guid("22222222-2222-2222-2222-222222222222"),
                            Ativo = true,
                            Cpf = "98765432100",
                            DataCriacao = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "joao.silva@gmail.com",
                            Genero = "Masculino",
                            Nascimento = new DateTime(1995, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "João Silva Santos",
                            Senha = "sRZL6wOaZHF0L6wOaZHF0L6wOaZHF0L6wOaZHF0L6wOaZHF="
                        });
                });

            modelBuilder.Entity("BROS_ECommerce.Domain.Entities.Carrinho", b =>
                {
                    b.HasOne("BROS_ECommerce.Domain.Entities.User", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("FK_Carrinhos_Usuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BROS_ECommerce.Domain.Entities.CarrinhoItem", b =>
                {
                    b.HasOne("BROS_ECommerce.Domain.Entities.Carrinho", "Carrinho")
                        .WithMany("Itens")
                        .HasForeignKey("IdCarrinho")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CarrinhoItens_Carrinho");

                    b.HasOne("BROS_ECommerce.Domain.Entities.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("IdProduto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CarrinhoItens_Produto");

                    b.Navigation("Carrinho");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("BROS_ECommerce.Domain.Entities.CategoriaProduto", b =>
                {
                    b.HasOne("BROS_ECommerce.Domain.Entities.Categoria", "Categoria")
                        .WithMany("CategoriaProdutos")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CategoriaProdutos_Categoria");

                    b.HasOne("BROS_ECommerce.Domain.Entities.Produto", "Produto")
                        .WithMany("CategoriaProdutos")
                        .HasForeignKey("IdProduto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CategoriaProdutos_Produto");

                    b.Navigation("Categoria");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("BROS_ECommerce.Domain.Entities.Estoque", b =>
                {
                    b.HasOne("BROS_ECommerce.Domain.Entities.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("IdProduto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Estoque_Produto");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("BROS_ECommerce.Domain.Entities.Pedido", b =>
                {
                    b.HasOne("BROS_ECommerce.Domain.Entities.User", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Pedidos_Usuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BROS_ECommerce.Domain.Entities.PedidoItem", b =>
                {
                    b.HasOne("BROS_ECommerce.Domain.Entities.Pedido", "Pedido")
                        .WithMany("PedidoItens")
                        .HasForeignKey("IdPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PedidoItens_Pedido");

                    b.HasOne("BROS_ECommerce.Domain.Entities.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("IdProduto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PedidoItens_Produto");

                    b.Navigation("Pedido");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("BROS_ECommerce.Domain.Entities.ProdutoImagem", b =>
                {
                    b.HasOne("BROS_ECommerce.Domain.Entities.Imagem", "Imagem")
                        .WithMany("ProdutoImagens")
                        .HasForeignKey("IdImagem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ProdutoImagens_Imagem");

                    b.HasOne("BROS_ECommerce.Domain.Entities.Produto", "Produto")
                        .WithMany("ProdutoImagens")
                        .HasForeignKey("IdProduto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ProdutoImagens_Produto");

                    b.Navigation("Imagem");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("BROS_ECommerce.Domain.Entities.Promocao", b =>
                {
                    b.HasOne("BROS_ECommerce.Domain.Entities.Produto", "Produto")
                        .WithMany("Promocoes")
                        .HasForeignKey("IdProduto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Promocoes_Produto");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("BROS_ECommerce.Domain.Entities.Carrinho", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("BROS_ECommerce.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("CategoriaProdutos");
                });

            modelBuilder.Entity("BROS_ECommerce.Domain.Entities.Imagem", b =>
                {
                    b.Navigation("ProdutoImagens");
                });

            modelBuilder.Entity("BROS_ECommerce.Domain.Entities.Pedido", b =>
                {
                    b.Navigation("PedidoItens");
                });

            modelBuilder.Entity("BROS_ECommerce.Domain.Entities.Produto", b =>
                {
                    b.Navigation("CategoriaProdutos");

                    b.Navigation("ProdutoImagens");

                    b.Navigation("Promocoes");
                });
#pragma warning restore 612, 618
        }
    }
}
