// <auto-generated />
using System;
using BROS_ECommerce.Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BROS_ECommerce.Infra.Migrations
{
    [DbContext(typeof(BrosContext))]
    [Migration("20250710173310_CreateImagemTables")]
    partial class CreateImagemTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BROS_ECommerce.Domain.Entities.Estoque", b =>
                {
                    b.Property<Guid>("IdEstoque")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdEstoque");

                    b.Property<Guid>("IdProduto")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdProduto");

                    b.Property<int>("Quantidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("Quantidade");

                    b.Property<DateTime>("UltimaAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("UltimaAtualizacao")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("IdEstoque");

                    b.HasIndex("IdProduto")
                        .IsUnique()
                        .HasDatabaseName("IX_Estoque_IdProduto");

                    b.HasIndex("Quantidade")
                        .HasDatabaseName("IX_Estoque_Quantidade");

                    b.HasIndex("UltimaAtualizacao")
                        .HasDatabaseName("IX_Estoque_UltimaAtualizacao");

                    b.ToTable("Estoque", (string)null);
                });

            modelBuilder.Entity("BROS_ECommerce.Domain.Entities.Imagem", b =>
                {
                    b.Property<Guid>("IdImagem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdImagem");

                    b.Property<string>("AltText")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("AltText");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Ativo");

                    b.Property<string>("CaminhoArquivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("CaminhoArquivo");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataAtualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("DataCriacao")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("NomeArquivo");

                    b.Property<long>("TamanhoArquivo")
                        .HasColumnType("bigint")
                        .HasColumnName("TamanhoArquivo");

                    b.Property<string>("TipoMime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("TipoMime");

                    b.HasKey("IdImagem");

                    b.HasIndex("Ativo")
                        .HasDatabaseName("IX_Imagens_Ativo");

                    b.HasIndex("DataCriacao")
                        .HasDatabaseName("IX_Imagens_DataCriacao");

                    b.HasIndex("NomeArquivo")
                        .HasDatabaseName("IX_Imagens_NomeArquivo");

                    b.HasIndex("TipoMime")
                        .HasDatabaseName("IX_Imagens_TipoMime");

                    b.ToTable("Imagens", (string)null);
                });

            modelBuilder.Entity("BROS_ECommerce.Domain.Entities.Produto", b =>
                {
                    b.Property<Guid>("IdProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdProduto");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("Descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Nome");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Preco");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Slug");

                    b.Property<string>("TituloDescricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("TituloDescricao");

                    b.HasKey("IdProduto");

                    b.HasIndex("Nome")
                        .HasDatabaseName("IX_Produtos_Nome");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("IX_Produtos_Slug");

                    b.ToTable("Produtos", (string)null);
                });

            modelBuilder.Entity("BROS_ECommerce.Domain.Entities.ProdutoImagem", b =>
                {
                    b.Property<Guid>("IdProdutoImagem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdProdutoImagem");

                    b.Property<DateTime>("DataAssociacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("DataAssociacao")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("IdImagem")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdImagem");

                    b.Property<Guid>("IdProduto")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdProduto");

                    b.Property<int>("Ordem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("Ordem");

                    b.Property<bool>("Principal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("Principal");

                    b.HasKey("IdProdutoImagem");

                    b.HasIndex("IdImagem")
                        .HasDatabaseName("IX_ProdutoImagens_IdImagem");

                    b.HasIndex("IdProduto")
                        .HasDatabaseName("IX_ProdutoImagens_IdProduto");

                    b.HasIndex("IdProduto", "Ordem")
                        .HasDatabaseName("IX_ProdutoImagens_IdProduto_Ordem");

                    b.HasIndex("IdProduto", "Principal")
                        .HasDatabaseName("IX_ProdutoImagens_UnicaPrincipal")
                        .HasFilter("Principal = 1");

                    b.ToTable("ProdutoImagens", (string)null);
                });

            modelBuilder.Entity("BROS_ECommerce.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("Nascimento")
                        .HasColumnType("date");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("IdUser");

                    b.HasIndex("Ativo")
                        .HasDatabaseName("IX_Users_Ativo");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Cpf");

                    b.HasIndex("DataCriacao")
                        .HasDatabaseName("IX_Users_DataCriacao");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            IdUser = new Guid("11111111-1111-1111-1111-111111111111"),
                            Ativo = true,
                            Cpf = "12345678901",
                            DataCriacao = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@bros.com",
                            Genero = "Masculino",
                            Nascimento = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Administrador Sistema",
                            Senha = "rQZK5vNzZGE9K5vNzZGE9K5vNzZGE9K5vNzZGE9K5vNzZGE="
                        },
                        new
                        {
                            IdUser = new Guid("22222222-2222-2222-2222-222222222222"),
                            Ativo = true,
                            Cpf = "98765432100",
                            DataCriacao = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "joao.silva@gmail.com",
                            Genero = "Masculino",
                            Nascimento = new DateTime(1995, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "João Silva Santos",
                            Senha = "sRZL6wOaZHF0L6wOaZHF0L6wOaZHF0L6wOaZHF0L6wOaZHF="
                        });
                });

            modelBuilder.Entity("BROS_ECommerce.Domain.Entities.Estoque", b =>
                {
                    b.HasOne("BROS_ECommerce.Domain.Entities.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("IdProduto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Estoque_Produto");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("BROS_ECommerce.Domain.Entities.ProdutoImagem", b =>
                {
                    b.HasOne("BROS_ECommerce.Domain.Entities.Imagem", "Imagem")
                        .WithMany("ProdutoImagens")
                        .HasForeignKey("IdImagem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ProdutoImagens_Imagem");

                    b.HasOne("BROS_ECommerce.Domain.Entities.Produto", "Produto")
                        .WithMany("ProdutoImagens")
                        .HasForeignKey("IdProduto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ProdutoImagens_Produto");

                    b.Navigation("Imagem");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("BROS_ECommerce.Domain.Entities.Imagem", b =>
                {
                    b.Navigation("ProdutoImagens");
                });

            modelBuilder.Entity("BROS_ECommerce.Domain.Entities.Produto", b =>
                {
                    b.Navigation("ProdutoImagens");
                });
#pragma warning restore 612, 618
        }
    }
}
